package com.chineseivy.dao;

import com.chineseivy.bean.Complain;
import com.chineseivy.bean.ComplainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    long countByExample(ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int deleteByExample(ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer complainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int insert(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int insertSelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    List<Complain> selectByExample(ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    Complain selectByPrimaryKey(Integer complainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Complain record, @Param("example") ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Complain record, @Param("example") ComplainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_complain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Complain record);
}