package com.chineseivy.dao;

import com.chineseivy.bean.CustomerAddress;
import com.chineseivy.bean.CustomerAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    long countByExample(CustomerAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int insert(CustomerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int insertSelective(CustomerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    List<CustomerAddress> selectByExample(CustomerAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    CustomerAddress selectByPrimaryKey(Integer addressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerAddress record, @Param("example") CustomerAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerAddress record, @Param("example") CustomerAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customerAddress
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerAddress record);
}