package com.chineseivy.dao;

import com.chineseivy.bean.Favourite;
import com.chineseivy.bean.FavouriteExample;
import com.chineseivy.bean.FavouriteKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavouriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    long countByExample(FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int deleteByExample(FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FavouriteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int insert(Favourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int insertSelective(Favourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    List<Favourite> selectByExample(FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    Favourite selectByPrimaryKey(FavouriteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Favourite record, @Param("example") FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Favourite record, @Param("example") FavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Favourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favourite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Favourite record);
}