package com.chineseivy.dao;

import com.chineseivy.bean.Good;
import com.chineseivy.bean.GoodExample;
import java.util.List;

import com.chineseivy.bean.GoodPackage;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface GoodMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     * @Decription 根据主键删除商品信息
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     * @Decription 插入商品信息
     * @mbg.generated
     */
    int insertSelective(Good record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     * @Decription 根据主键得到商品信息
     * @mbg.generated
     */
    GoodPackage selectByPrimaryKey(Integer goodid);

    /**
     * @Decription 选择全部商品
     * @return 返回集合
     */
    List<GoodPackage> selectAllGoods();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     * @Decription 根据主键更新并检查所否每个属性都有更新
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Good record);

    List<GoodPackage> selectByGoodState(int goodState);

    int maxId();

    int selectShopId(int goodId);

}