package com.chineseivy.dao;

import com.chineseivy.bean.GoodToOrderExample;
import com.chineseivy.bean.GoodToOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodToOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    long countByExample(GoodToOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    int deleteByExample(GoodToOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GoodToOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    int insert(GoodToOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    int insertSelective(GoodToOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    List<GoodToOrderKey> selectByExample(GoodToOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodToOrderKey record, @Param("example") GoodToOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FK_GoodToOrder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodToOrderKey record, @Param("example") GoodToOrderExample example);
}