package com.chineseivy.dao;

import com.chineseivy.bean.PaidWay;
import com.chineseivy.bean.PaidWayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaidWayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    long countByExample(PaidWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int deleteByExample(PaidWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer paidid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int insert(PaidWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int insertSelective(PaidWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    List<PaidWay> selectByExample(PaidWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    PaidWay selectByPrimaryKey(Integer paidid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaidWay record, @Param("example") PaidWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaidWay record, @Param("example") PaidWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaidWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paidWay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaidWay record);
}