package com.chineseivy.dao;

import com.chineseivy.bean.ShoppingCart;
import com.chineseivy.bean.ShoppingCartExample;
import com.chineseivy.bean.ShoppingCartKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    long countByExample(ShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int deleteByExample(ShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ShoppingCartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int insert(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int insertSelective(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    List<ShoppingCart> selectByExample(ShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    ShoppingCart selectByPrimaryKey(ShoppingCartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShoppingCart record, @Param("example") ShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShoppingCart record, @Param("example") ShoppingCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shoppingCart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShoppingCart record);
}