package com.chineseivy.dao;

import com.chineseivy.bean.Warehouse;
import com.chineseivy.bean.WarehouseExample;
import com.chineseivy.bean.WarehouseKey;
import java.util.List;

import com.chineseivy.bean.WarehousePackage;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface WarehouseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(WarehouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbg.generated
     */
    int insertSelective(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbg.generated
     */
    WarehousePackage selectByPrimaryKey(Integer goodid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warehouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Warehouse record);

    /**
    * @Program: WarehouseMapper.java
    * @Method:
    * @Description: 选择全部库存信息
    * @Author: Shiming Lee
    * @Create: 2018/5/25 20:14
    * @params:
    * @returns:
    **/
    List<WarehousePackage> selectAllWarehouse();
}