package com.chineseivy.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public ActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActivityidIsNull() {
            addCriterion("activityId is null");
            return (Criteria) this;
        }

        public Criteria andActivityidIsNotNull() {
            addCriterion("activityId is not null");
            return (Criteria) this;
        }

        public Criteria andActivityidEqualTo(Integer value) {
            addCriterion("activityId =", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotEqualTo(Integer value) {
            addCriterion("activityId <>", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidGreaterThan(Integer value) {
            addCriterion("activityId >", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("activityId >=", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidLessThan(Integer value) {
            addCriterion("activityId <", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidLessThanOrEqualTo(Integer value) {
            addCriterion("activityId <=", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidIn(List<Integer> values) {
            addCriterion("activityId in", values, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotIn(List<Integer> values) {
            addCriterion("activityId not in", values, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidBetween(Integer value1, Integer value2) {
            addCriterion("activityId between", value1, value2, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotBetween(Integer value1, Integer value2) {
            addCriterion("activityId not between", value1, value2, "activityid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidIsNull() {
            addCriterion("goodClassId is null");
            return (Criteria) this;
        }

        public Criteria andGoodclassidIsNotNull() {
            addCriterion("goodClassId is not null");
            return (Criteria) this;
        }

        public Criteria andGoodclassidEqualTo(Integer value) {
            addCriterion("goodClassId =", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidNotEqualTo(Integer value) {
            addCriterion("goodClassId <>", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidGreaterThan(Integer value) {
            addCriterion("goodClassId >", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodClassId >=", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidLessThan(Integer value) {
            addCriterion("goodClassId <", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidLessThanOrEqualTo(Integer value) {
            addCriterion("goodClassId <=", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidIn(List<Integer> values) {
            addCriterion("goodClassId in", values, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidNotIn(List<Integer> values) {
            addCriterion("goodClassId not in", values, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidBetween(Integer value1, Integer value2) {
            addCriterion("goodClassId between", value1, value2, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodClassId not between", value1, value2, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andActivitythemeIsNull() {
            addCriterion("activityTheme is null");
            return (Criteria) this;
        }

        public Criteria andActivitythemeIsNotNull() {
            addCriterion("activityTheme is not null");
            return (Criteria) this;
        }

        public Criteria andActivitythemeEqualTo(String value) {
            addCriterion("activityTheme =", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeNotEqualTo(String value) {
            addCriterion("activityTheme <>", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeGreaterThan(String value) {
            addCriterion("activityTheme >", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeGreaterThanOrEqualTo(String value) {
            addCriterion("activityTheme >=", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeLessThan(String value) {
            addCriterion("activityTheme <", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeLessThanOrEqualTo(String value) {
            addCriterion("activityTheme <=", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeLike(String value) {
            addCriterion("activityTheme like", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeNotLike(String value) {
            addCriterion("activityTheme not like", value, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeIn(List<String> values) {
            addCriterion("activityTheme in", values, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeNotIn(List<String> values) {
            addCriterion("activityTheme not in", values, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeBetween(String value1, String value2) {
            addCriterion("activityTheme between", value1, value2, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitythemeNotBetween(String value1, String value2) {
            addCriterion("activityTheme not between", value1, value2, "activitytheme");
            return (Criteria) this;
        }

        public Criteria andActivitytextIsNull() {
            addCriterion("activityText is null");
            return (Criteria) this;
        }

        public Criteria andActivitytextIsNotNull() {
            addCriterion("activityText is not null");
            return (Criteria) this;
        }

        public Criteria andActivitytextEqualTo(String value) {
            addCriterion("activityText =", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextNotEqualTo(String value) {
            addCriterion("activityText <>", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextGreaterThan(String value) {
            addCriterion("activityText >", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextGreaterThanOrEqualTo(String value) {
            addCriterion("activityText >=", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextLessThan(String value) {
            addCriterion("activityText <", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextLessThanOrEqualTo(String value) {
            addCriterion("activityText <=", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextLike(String value) {
            addCriterion("activityText like", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextNotLike(String value) {
            addCriterion("activityText not like", value, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextIn(List<String> values) {
            addCriterion("activityText in", values, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextNotIn(List<String> values) {
            addCriterion("activityText not in", values, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextBetween(String value1, String value2) {
            addCriterion("activityText between", value1, value2, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivitytextNotBetween(String value1, String value2) {
            addCriterion("activityText not between", value1, value2, "activitytext");
            return (Criteria) this;
        }

        public Criteria andActivityimgIsNull() {
            addCriterion("activityImg is null");
            return (Criteria) this;
        }

        public Criteria andActivityimgIsNotNull() {
            addCriterion("activityImg is not null");
            return (Criteria) this;
        }

        public Criteria andActivityimgEqualTo(String value) {
            addCriterion("activityImg =", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgNotEqualTo(String value) {
            addCriterion("activityImg <>", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgGreaterThan(String value) {
            addCriterion("activityImg >", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgGreaterThanOrEqualTo(String value) {
            addCriterion("activityImg >=", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgLessThan(String value) {
            addCriterion("activityImg <", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgLessThanOrEqualTo(String value) {
            addCriterion("activityImg <=", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgLike(String value) {
            addCriterion("activityImg like", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgNotLike(String value) {
            addCriterion("activityImg not like", value, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgIn(List<String> values) {
            addCriterion("activityImg in", values, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgNotIn(List<String> values) {
            addCriterion("activityImg not in", values, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgBetween(String value1, String value2) {
            addCriterion("activityImg between", value1, value2, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivityimgNotBetween(String value1, String value2) {
            addCriterion("activityImg not between", value1, value2, "activityimg");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeIsNull() {
            addCriterion("activityStartTime is null");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeIsNotNull() {
            addCriterion("activityStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeEqualTo(Date value) {
            addCriterion("activityStartTime =", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeNotEqualTo(Date value) {
            addCriterion("activityStartTime <>", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeGreaterThan(Date value) {
            addCriterion("activityStartTime >", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("activityStartTime >=", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeLessThan(Date value) {
            addCriterion("activityStartTime <", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeLessThanOrEqualTo(Date value) {
            addCriterion("activityStartTime <=", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeIn(List<Date> values) {
            addCriterion("activityStartTime in", values, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeNotIn(List<Date> values) {
            addCriterion("activityStartTime not in", values, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeBetween(Date value1, Date value2) {
            addCriterion("activityStartTime between", value1, value2, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeNotBetween(Date value1, Date value2) {
            addCriterion("activityStartTime not between", value1, value2, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeIsNull() {
            addCriterion("activityEndTime is null");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeIsNotNull() {
            addCriterion("activityEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeEqualTo(Date value) {
            addCriterion("activityEndTime =", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeNotEqualTo(Date value) {
            addCriterion("activityEndTime <>", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeGreaterThan(Date value) {
            addCriterion("activityEndTime >", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("activityEndTime >=", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeLessThan(Date value) {
            addCriterion("activityEndTime <", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeLessThanOrEqualTo(Date value) {
            addCriterion("activityEndTime <=", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeIn(List<Date> values) {
            addCriterion("activityEndTime in", values, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeNotIn(List<Date> values) {
            addCriterion("activityEndTime not in", values, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeBetween(Date value1, Date value2) {
            addCriterion("activityEndTime between", value1, value2, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeNotBetween(Date value1, Date value2) {
            addCriterion("activityEndTime not between", value1, value2, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andAimIsNull() {
            addCriterion("aim is null");
            return (Criteria) this;
        }

        public Criteria andAimIsNotNull() {
            addCriterion("aim is not null");
            return (Criteria) this;
        }

        public Criteria andAimEqualTo(Double value) {
            addCriterion("aim =", value, "aim");
            return (Criteria) this;
        }

        public Criteria andAimNotEqualTo(Double value) {
            addCriterion("aim <>", value, "aim");
            return (Criteria) this;
        }

        public Criteria andAimGreaterThan(Double value) {
            addCriterion("aim >", value, "aim");
            return (Criteria) this;
        }

        public Criteria andAimGreaterThanOrEqualTo(Double value) {
            addCriterion("aim >=", value, "aim");
            return (Criteria) this;
        }

        public Criteria andAimLessThan(Double value) {
            addCriterion("aim <", value, "aim");
            return (Criteria) this;
        }

        public Criteria andAimLessThanOrEqualTo(Double value) {
            addCriterion("aim <=", value, "aim");
            return (Criteria) this;
        }

        public Criteria andAimIn(List<Double> values) {
            addCriterion("aim in", values, "aim");
            return (Criteria) this;
        }

        public Criteria andAimNotIn(List<Double> values) {
            addCriterion("aim not in", values, "aim");
            return (Criteria) this;
        }

        public Criteria andAimBetween(Double value1, Double value2) {
            addCriterion("aim between", value1, value2, "aim");
            return (Criteria) this;
        }

        public Criteria andAimNotBetween(Double value1, Double value2) {
            addCriterion("aim not between", value1, value2, "aim");
            return (Criteria) this;
        }

        public Criteria andReduceIsNull() {
            addCriterion("reduce is null");
            return (Criteria) this;
        }

        public Criteria andReduceIsNotNull() {
            addCriterion("reduce is not null");
            return (Criteria) this;
        }

        public Criteria andReduceEqualTo(Double value) {
            addCriterion("reduce =", value, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceNotEqualTo(Double value) {
            addCriterion("reduce <>", value, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceGreaterThan(Double value) {
            addCriterion("reduce >", value, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceGreaterThanOrEqualTo(Double value) {
            addCriterion("reduce >=", value, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceLessThan(Double value) {
            addCriterion("reduce <", value, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceLessThanOrEqualTo(Double value) {
            addCriterion("reduce <=", value, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceIn(List<Double> values) {
            addCriterion("reduce in", values, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceNotIn(List<Double> values) {
            addCriterion("reduce not in", values, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceBetween(Double value1, Double value2) {
            addCriterion("reduce between", value1, value2, "reduce");
            return (Criteria) this;
        }

        public Criteria andReduceNotBetween(Double value1, Double value2) {
            addCriterion("reduce not between", value1, value2, "reduce");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_activity
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}