package com.chineseivy.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public CommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommentidIsNull() {
            addCriterion("commentId is null");
            return (Criteria) this;
        }

        public Criteria andCommentidIsNotNull() {
            addCriterion("commentId is not null");
            return (Criteria) this;
        }

        public Criteria andCommentidEqualTo(Integer value) {
            addCriterion("commentId =", value, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidNotEqualTo(Integer value) {
            addCriterion("commentId <>", value, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidGreaterThan(Integer value) {
            addCriterion("commentId >", value, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentId >=", value, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidLessThan(Integer value) {
            addCriterion("commentId <", value, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidLessThanOrEqualTo(Integer value) {
            addCriterion("commentId <=", value, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidIn(List<Integer> values) {
            addCriterion("commentId in", values, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidNotIn(List<Integer> values) {
            addCriterion("commentId not in", values, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidBetween(Integer value1, Integer value2) {
            addCriterion("commentId between", value1, value2, "commentid");
            return (Criteria) this;
        }

        public Criteria andCommentidNotBetween(Integer value1, Integer value2) {
            addCriterion("commentId not between", value1, value2, "commentid");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andCommenttextIsNull() {
            addCriterion("commentText is null");
            return (Criteria) this;
        }

        public Criteria andCommenttextIsNotNull() {
            addCriterion("commentText is not null");
            return (Criteria) this;
        }

        public Criteria andCommenttextEqualTo(String value) {
            addCriterion("commentText =", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextNotEqualTo(String value) {
            addCriterion("commentText <>", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextGreaterThan(String value) {
            addCriterion("commentText >", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextGreaterThanOrEqualTo(String value) {
            addCriterion("commentText >=", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextLessThan(String value) {
            addCriterion("commentText <", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextLessThanOrEqualTo(String value) {
            addCriterion("commentText <=", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextLike(String value) {
            addCriterion("commentText like", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextNotLike(String value) {
            addCriterion("commentText not like", value, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextIn(List<String> values) {
            addCriterion("commentText in", values, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextNotIn(List<String> values) {
            addCriterion("commentText not in", values, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextBetween(String value1, String value2) {
            addCriterion("commentText between", value1, value2, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommenttextNotBetween(String value1, String value2) {
            addCriterion("commentText not between", value1, value2, "commenttext");
            return (Criteria) this;
        }

        public Criteria andCommentreplyIsNull() {
            addCriterion("commentReply is null");
            return (Criteria) this;
        }

        public Criteria andCommentreplyIsNotNull() {
            addCriterion("commentReply is not null");
            return (Criteria) this;
        }

        public Criteria andCommentreplyEqualTo(String value) {
            addCriterion("commentReply =", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyNotEqualTo(String value) {
            addCriterion("commentReply <>", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyGreaterThan(String value) {
            addCriterion("commentReply >", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyGreaterThanOrEqualTo(String value) {
            addCriterion("commentReply >=", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyLessThan(String value) {
            addCriterion("commentReply <", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyLessThanOrEqualTo(String value) {
            addCriterion("commentReply <=", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyLike(String value) {
            addCriterion("commentReply like", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyNotLike(String value) {
            addCriterion("commentReply not like", value, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyIn(List<String> values) {
            addCriterion("commentReply in", values, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyNotIn(List<String> values) {
            addCriterion("commentReply not in", values, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyBetween(String value1, String value2) {
            addCriterion("commentReply between", value1, value2, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommentreplyNotBetween(String value1, String value2) {
            addCriterion("commentReply not between", value1, value2, "commentreply");
            return (Criteria) this;
        }

        public Criteria andCommenttimeIsNull() {
            addCriterion("commentTime is null");
            return (Criteria) this;
        }

        public Criteria andCommenttimeIsNotNull() {
            addCriterion("commentTime is not null");
            return (Criteria) this;
        }

        public Criteria andCommenttimeEqualTo(Date value) {
            addCriterion("commentTime =", value, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeNotEqualTo(Date value) {
            addCriterion("commentTime <>", value, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeGreaterThan(Date value) {
            addCriterion("commentTime >", value, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("commentTime >=", value, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeLessThan(Date value) {
            addCriterion("commentTime <", value, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeLessThanOrEqualTo(Date value) {
            addCriterion("commentTime <=", value, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeIn(List<Date> values) {
            addCriterion("commentTime in", values, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeNotIn(List<Date> values) {
            addCriterion("commentTime not in", values, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeBetween(Date value1, Date value2) {
            addCriterion("commentTime between", value1, value2, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommenttimeNotBetween(Date value1, Date value2) {
            addCriterion("commentTime not between", value1, value2, "commenttime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeIsNull() {
            addCriterion("commentReplyTime is null");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeIsNotNull() {
            addCriterion("commentReplyTime is not null");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeEqualTo(Date value) {
            addCriterion("commentReplyTime =", value, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeNotEqualTo(Date value) {
            addCriterion("commentReplyTime <>", value, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeGreaterThan(Date value) {
            addCriterion("commentReplyTime >", value, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("commentReplyTime >=", value, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeLessThan(Date value) {
            addCriterion("commentReplyTime <", value, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeLessThanOrEqualTo(Date value) {
            addCriterion("commentReplyTime <=", value, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeIn(List<Date> values) {
            addCriterion("commentReplyTime in", values, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeNotIn(List<Date> values) {
            addCriterion("commentReplyTime not in", values, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeBetween(Date value1, Date value2) {
            addCriterion("commentReplyTime between", value1, value2, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentreplytimeNotBetween(Date value1, Date value2) {
            addCriterion("commentReplyTime not between", value1, value2, "commentreplytime");
            return (Criteria) this;
        }

        public Criteria andCommentstarIsNull() {
            addCriterion("commentStar is null");
            return (Criteria) this;
        }

        public Criteria andCommentstarIsNotNull() {
            addCriterion("commentStar is not null");
            return (Criteria) this;
        }

        public Criteria andCommentstarEqualTo(Integer value) {
            addCriterion("commentStar =", value, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarNotEqualTo(Integer value) {
            addCriterion("commentStar <>", value, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarGreaterThan(Integer value) {
            addCriterion("commentStar >", value, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentStar >=", value, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarLessThan(Integer value) {
            addCriterion("commentStar <", value, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarLessThanOrEqualTo(Integer value) {
            addCriterion("commentStar <=", value, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarIn(List<Integer> values) {
            addCriterion("commentStar in", values, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarNotIn(List<Integer> values) {
            addCriterion("commentStar not in", values, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarBetween(Integer value1, Integer value2) {
            addCriterion("commentStar between", value1, value2, "commentstar");
            return (Criteria) this;
        }

        public Criteria andCommentstarNotBetween(Integer value1, Integer value2) {
            addCriterion("commentStar not between", value1, value2, "commentstar");
            return (Criteria) this;
        }

        public Criteria andAgreeIsNull() {
            addCriterion("agree is null");
            return (Criteria) this;
        }

        public Criteria andAgreeIsNotNull() {
            addCriterion("agree is not null");
            return (Criteria) this;
        }

        public Criteria andAgreeEqualTo(Integer value) {
            addCriterion("agree =", value, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeNotEqualTo(Integer value) {
            addCriterion("agree <>", value, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeGreaterThan(Integer value) {
            addCriterion("agree >", value, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("agree >=", value, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeLessThan(Integer value) {
            addCriterion("agree <", value, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeLessThanOrEqualTo(Integer value) {
            addCriterion("agree <=", value, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeIn(List<Integer> values) {
            addCriterion("agree in", values, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeNotIn(List<Integer> values) {
            addCriterion("agree not in", values, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeBetween(Integer value1, Integer value2) {
            addCriterion("agree between", value1, value2, "agree");
            return (Criteria) this;
        }

        public Criteria andAgreeNotBetween(Integer value1, Integer value2) {
            addCriterion("agree not between", value1, value2, "agree");
            return (Criteria) this;
        }

        public Criteria andCommentstateIsNull() {
            addCriterion("commentState is null");
            return (Criteria) this;
        }

        public Criteria andCommentstateIsNotNull() {
            addCriterion("commentState is not null");
            return (Criteria) this;
        }

        public Criteria andCommentstateEqualTo(Integer value) {
            addCriterion("commentState =", value, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateNotEqualTo(Integer value) {
            addCriterion("commentState <>", value, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateGreaterThan(Integer value) {
            addCriterion("commentState >", value, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentState >=", value, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateLessThan(Integer value) {
            addCriterion("commentState <", value, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateLessThanOrEqualTo(Integer value) {
            addCriterion("commentState <=", value, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateIn(List<Integer> values) {
            addCriterion("commentState in", values, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateNotIn(List<Integer> values) {
            addCriterion("commentState not in", values, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateBetween(Integer value1, Integer value2) {
            addCriterion("commentState between", value1, value2, "commentstate");
            return (Criteria) this;
        }

        public Criteria andCommentstateNotBetween(Integer value1, Integer value2) {
            addCriterion("commentState not between", value1, value2, "commentstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_comment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_comment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}