package com.chineseivy.bean;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentId
     *
     * @mbg.generated
     */
    private Integer commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.orderId
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentText
     *
     * @mbg.generated
     */
    private String commenttext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentReply
     *
     * @mbg.generated
     */
    private String commentreply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentTime
     *
     * @mbg.generated
     */
    private Date commenttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentReplyTime
     *
     * @mbg.generated
     */
    private Date commentreplytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentStar
     *
     * @mbg.generated
     */
    private Integer commentstar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.agree
     *
     * @mbg.generated
     */
    private Integer agree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentState
     *
     * @mbg.generated
     */
    private Integer commentstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentId
     *
     * @return the value of t_comment.commentId
     *
     * @mbg.generated
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentId
     *
     * @param commentid the value for t_comment.commentId
     *
     * @mbg.generated
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.orderId
     *
     * @return the value of t_comment.orderId
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.orderId
     *
     * @param orderid the value for t_comment.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentText
     *
     * @return the value of t_comment.commentText
     *
     * @mbg.generated
     */
    public String getCommenttext() {
        return commenttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentText
     *
     * @param commenttext the value for t_comment.commentText
     *
     * @mbg.generated
     */
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext == null ? null : commenttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentReply
     *
     * @return the value of t_comment.commentReply
     *
     * @mbg.generated
     */
    public String getCommentreply() {
        return commentreply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentReply
     *
     * @param commentreply the value for t_comment.commentReply
     *
     * @mbg.generated
     */
    public void setCommentreply(String commentreply) {
        this.commentreply = commentreply == null ? null : commentreply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentTime
     *
     * @return the value of t_comment.commentTime
     *
     * @mbg.generated
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentTime
     *
     * @param commenttime the value for t_comment.commentTime
     *
     * @mbg.generated
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentReplyTime
     *
     * @return the value of t_comment.commentReplyTime
     *
     * @mbg.generated
     */
    public Date getCommentreplytime() {
        return commentreplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentReplyTime
     *
     * @param commentreplytime the value for t_comment.commentReplyTime
     *
     * @mbg.generated
     */
    public void setCommentreplytime(Date commentreplytime) {
        this.commentreplytime = commentreplytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentStar
     *
     * @return the value of t_comment.commentStar
     *
     * @mbg.generated
     */
    public Integer getCommentstar() {
        return commentstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentStar
     *
     * @param commentstar the value for t_comment.commentStar
     *
     * @mbg.generated
     */
    public void setCommentstar(Integer commentstar) {
        this.commentstar = commentstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.agree
     *
     * @return the value of t_comment.agree
     *
     * @mbg.generated
     */
    public Integer getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.agree
     *
     * @param agree the value for t_comment.agree
     *
     * @mbg.generated
     */
    public void setAgree(Integer agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentState
     *
     * @return the value of t_comment.commentState
     *
     * @mbg.generated
     */
    public Integer getCommentstate() {
        return commentstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentState
     *
     * @param commentstate the value for t_comment.commentState
     *
     * @mbg.generated
     */
    public void setCommentstate(Integer commentstate) {
        this.commentstate = commentstate;
    }
}