package com.chineseivy.bean;

import java.util.Date;

public class Complain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainId
     *
     * @mbg.generated
     */
    private Integer complainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.orderId
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainReason
     *
     * @mbg.generated
     */
    private String complainreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainImage
     *
     * @mbg.generated
     */
    private String complainimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainTime
     *
     * @mbg.generated
     */
    private Date complaintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainReply
     *
     * @mbg.generated
     */
    private String complainreply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.replyTime
     *
     * @mbg.generated
     */
    private Date replytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainState
     *
     * @mbg.generated
     */
    private Integer complainstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainResult
     *
     * @mbg.generated
     */
    private String complainresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.finishState
     *
     * @mbg.generated
     */
    private Integer finishstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.complainFinish
     *
     * @mbg.generated
     */
    private String complainfinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_complain.finishTime
     *
     * @mbg.generated
     */
    private Date finishtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainId
     *
     * @return the value of t_complain.complainId
     *
     * @mbg.generated
     */
    public Integer getComplainid() {
        return complainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainId
     *
     * @param complainid the value for t_complain.complainId
     *
     * @mbg.generated
     */
    public void setComplainid(Integer complainid) {
        this.complainid = complainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.orderId
     *
     * @return the value of t_complain.orderId
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.orderId
     *
     * @param orderid the value for t_complain.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainReason
     *
     * @return the value of t_complain.complainReason
     *
     * @mbg.generated
     */
    public String getComplainreason() {
        return complainreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainReason
     *
     * @param complainreason the value for t_complain.complainReason
     *
     * @mbg.generated
     */
    public void setComplainreason(String complainreason) {
        this.complainreason = complainreason == null ? null : complainreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainImage
     *
     * @return the value of t_complain.complainImage
     *
     * @mbg.generated
     */
    public String getComplainimage() {
        return complainimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainImage
     *
     * @param complainimage the value for t_complain.complainImage
     *
     * @mbg.generated
     */
    public void setComplainimage(String complainimage) {
        this.complainimage = complainimage == null ? null : complainimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainTime
     *
     * @return the value of t_complain.complainTime
     *
     * @mbg.generated
     */
    public Date getComplaintime() {
        return complaintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainTime
     *
     * @param complaintime the value for t_complain.complainTime
     *
     * @mbg.generated
     */
    public void setComplaintime(Date complaintime) {
        this.complaintime = complaintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainReply
     *
     * @return the value of t_complain.complainReply
     *
     * @mbg.generated
     */
    public String getComplainreply() {
        return complainreply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainReply
     *
     * @param complainreply the value for t_complain.complainReply
     *
     * @mbg.generated
     */
    public void setComplainreply(String complainreply) {
        this.complainreply = complainreply == null ? null : complainreply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.replyTime
     *
     * @return the value of t_complain.replyTime
     *
     * @mbg.generated
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.replyTime
     *
     * @param replytime the value for t_complain.replyTime
     *
     * @mbg.generated
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainState
     *
     * @return the value of t_complain.complainState
     *
     * @mbg.generated
     */
    public Integer getComplainstate() {
        return complainstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainState
     *
     * @param complainstate the value for t_complain.complainState
     *
     * @mbg.generated
     */
    public void setComplainstate(Integer complainstate) {
        this.complainstate = complainstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainResult
     *
     * @return the value of t_complain.complainResult
     *
     * @mbg.generated
     */
    public String getComplainresult() {
        return complainresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainResult
     *
     * @param complainresult the value for t_complain.complainResult
     *
     * @mbg.generated
     */
    public void setComplainresult(String complainresult) {
        this.complainresult = complainresult == null ? null : complainresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.finishState
     *
     * @return the value of t_complain.finishState
     *
     * @mbg.generated
     */
    public Integer getFinishstate() {
        return finishstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.finishState
     *
     * @param finishstate the value for t_complain.finishState
     *
     * @mbg.generated
     */
    public void setFinishstate(Integer finishstate) {
        this.finishstate = finishstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.complainFinish
     *
     * @return the value of t_complain.complainFinish
     *
     * @mbg.generated
     */
    public String getComplainfinish() {
        return complainfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.complainFinish
     *
     * @param complainfinish the value for t_complain.complainFinish
     *
     * @mbg.generated
     */
    public void setComplainfinish(String complainfinish) {
        this.complainfinish = complainfinish == null ? null : complainfinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_complain.finishTime
     *
     * @return the value of t_complain.finishTime
     *
     * @mbg.generated
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_complain.finishTime
     *
     * @param finishtime the value for t_complain.finishTime
     *
     * @mbg.generated
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }
}