package com.chineseivy.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustomeridIsNull() {
            addCriterion("customerId is null");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNotNull() {
            addCriterion("customerId is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeridEqualTo(Integer value) {
            addCriterion("customerId =", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotEqualTo(Integer value) {
            addCriterion("customerId <>", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThan(Integer value) {
            addCriterion("customerId >", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("customerId >=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThan(Integer value) {
            addCriterion("customerId <", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThanOrEqualTo(Integer value) {
            addCriterion("customerId <=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIn(List<Integer> values) {
            addCriterion("customerId in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotIn(List<Integer> values) {
            addCriterion("customerId not in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridBetween(Integer value1, Integer value2) {
            addCriterion("customerId between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotBetween(Integer value1, Integer value2) {
            addCriterion("customerId not between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andPaididIsNull() {
            addCriterion("paidId is null");
            return (Criteria) this;
        }

        public Criteria andPaididIsNotNull() {
            addCriterion("paidId is not null");
            return (Criteria) this;
        }

        public Criteria andPaididEqualTo(Integer value) {
            addCriterion("paidId =", value, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididNotEqualTo(Integer value) {
            addCriterion("paidId <>", value, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididGreaterThan(Integer value) {
            addCriterion("paidId >", value, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididGreaterThanOrEqualTo(Integer value) {
            addCriterion("paidId >=", value, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididLessThan(Integer value) {
            addCriterion("paidId <", value, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididLessThanOrEqualTo(Integer value) {
            addCriterion("paidId <=", value, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididIn(List<Integer> values) {
            addCriterion("paidId in", values, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididNotIn(List<Integer> values) {
            addCriterion("paidId not in", values, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididBetween(Integer value1, Integer value2) {
            addCriterion("paidId between", value1, value2, "paidid");
            return (Criteria) this;
        }

        public Criteria andPaididNotBetween(Integer value1, Integer value2) {
            addCriterion("paidId not between", value1, value2, "paidid");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNull() {
            addCriterion("customerName is null");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNotNull() {
            addCriterion("customerName is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernameEqualTo(String value) {
            addCriterion("customerName =", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotEqualTo(String value) {
            addCriterion("customerName <>", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThan(String value) {
            addCriterion("customerName >", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThanOrEqualTo(String value) {
            addCriterion("customerName >=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThan(String value) {
            addCriterion("customerName <", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThanOrEqualTo(String value) {
            addCriterion("customerName <=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLike(String value) {
            addCriterion("customerName like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotLike(String value) {
            addCriterion("customerName not like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameIn(List<String> values) {
            addCriterion("customerName in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotIn(List<String> values) {
            addCriterion("customerName not in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameBetween(String value1, String value2) {
            addCriterion("customerName between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotBetween(String value1, String value2) {
            addCriterion("customerName not between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordIsNull() {
            addCriterion("customerPassword is null");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordIsNotNull() {
            addCriterion("customerPassword is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordEqualTo(String value) {
            addCriterion("customerPassword =", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordNotEqualTo(String value) {
            addCriterion("customerPassword <>", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordGreaterThan(String value) {
            addCriterion("customerPassword >", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("customerPassword >=", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordLessThan(String value) {
            addCriterion("customerPassword <", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordLessThanOrEqualTo(String value) {
            addCriterion("customerPassword <=", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordLike(String value) {
            addCriterion("customerPassword like", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordNotLike(String value) {
            addCriterion("customerPassword not like", value, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordIn(List<String> values) {
            addCriterion("customerPassword in", values, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordNotIn(List<String> values) {
            addCriterion("customerPassword not in", values, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordBetween(String value1, String value2) {
            addCriterion("customerPassword between", value1, value2, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomerpasswordNotBetween(String value1, String value2) {
            addCriterion("customerPassword not between", value1, value2, "customerpassword");
            return (Criteria) this;
        }

        public Criteria andCustomertelIsNull() {
            addCriterion("customerTel is null");
            return (Criteria) this;
        }

        public Criteria andCustomertelIsNotNull() {
            addCriterion("customerTel is not null");
            return (Criteria) this;
        }

        public Criteria andCustomertelEqualTo(String value) {
            addCriterion("customerTel =", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelNotEqualTo(String value) {
            addCriterion("customerTel <>", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelGreaterThan(String value) {
            addCriterion("customerTel >", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelGreaterThanOrEqualTo(String value) {
            addCriterion("customerTel >=", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelLessThan(String value) {
            addCriterion("customerTel <", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelLessThanOrEqualTo(String value) {
            addCriterion("customerTel <=", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelLike(String value) {
            addCriterion("customerTel like", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelNotLike(String value) {
            addCriterion("customerTel not like", value, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelIn(List<String> values) {
            addCriterion("customerTel in", values, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelNotIn(List<String> values) {
            addCriterion("customerTel not in", values, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelBetween(String value1, String value2) {
            addCriterion("customerTel between", value1, value2, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomertelNotBetween(String value1, String value2) {
            addCriterion("customerTel not between", value1, value2, "customertel");
            return (Criteria) this;
        }

        public Criteria andCustomerstarIsNull() {
            addCriterion("customerStar is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstarIsNotNull() {
            addCriterion("customerStar is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstarEqualTo(Integer value) {
            addCriterion("customerStar =", value, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarNotEqualTo(Integer value) {
            addCriterion("customerStar <>", value, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarGreaterThan(Integer value) {
            addCriterion("customerStar >", value, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarGreaterThanOrEqualTo(Integer value) {
            addCriterion("customerStar >=", value, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarLessThan(Integer value) {
            addCriterion("customerStar <", value, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarLessThanOrEqualTo(Integer value) {
            addCriterion("customerStar <=", value, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarIn(List<Integer> values) {
            addCriterion("customerStar in", values, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarNotIn(List<Integer> values) {
            addCriterion("customerStar not in", values, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarBetween(Integer value1, Integer value2) {
            addCriterion("customerStar between", value1, value2, "customerstar");
            return (Criteria) this;
        }

        public Criteria andCustomerstarNotBetween(Integer value1, Integer value2) {
            addCriterion("customerStar not between", value1, value2, "customerstar");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIsNull() {
            addCriterion("registerTime is null");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIsNotNull() {
            addCriterion("registerTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegistertimeEqualTo(Date value) {
            addCriterion("registerTime =", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotEqualTo(Date value) {
            addCriterion("registerTime <>", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeGreaterThan(Date value) {
            addCriterion("registerTime >", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("registerTime >=", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeLessThan(Date value) {
            addCriterion("registerTime <", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeLessThanOrEqualTo(Date value) {
            addCriterion("registerTime <=", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIn(List<Date> values) {
            addCriterion("registerTime in", values, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotIn(List<Date> values) {
            addCriterion("registerTime not in", values, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeBetween(Date value1, Date value2) {
            addCriterion("registerTime between", value1, value2, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotBetween(Date value1, Date value2) {
            addCriterion("registerTime not between", value1, value2, "registertime");
            return (Criteria) this;
        }

        public Criteria andCustomerstateIsNull() {
            addCriterion("customerState is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstateIsNotNull() {
            addCriterion("customerState is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstateEqualTo(Integer value) {
            addCriterion("customerState =", value, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateNotEqualTo(Integer value) {
            addCriterion("customerState <>", value, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateGreaterThan(Integer value) {
            addCriterion("customerState >", value, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("customerState >=", value, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateLessThan(Integer value) {
            addCriterion("customerState <", value, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateLessThanOrEqualTo(Integer value) {
            addCriterion("customerState <=", value, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateIn(List<Integer> values) {
            addCriterion("customerState in", values, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateNotIn(List<Integer> values) {
            addCriterion("customerState not in", values, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateBetween(Integer value1, Integer value2) {
            addCriterion("customerState between", value1, value2, "customerstate");
            return (Criteria) this;
        }

        public Criteria andCustomerstateNotBetween(Integer value1, Integer value2) {
            addCriterion("customerState not between", value1, value2, "customerstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}