package com.chineseivy.bean;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerId
     *
     * @mbg.generated
     */
    private Integer customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.paidId
     *
     * @mbg.generated
     */
    private Integer paidid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerName
     *
     * @mbg.generated
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerPassword
     *
     * @mbg.generated
     */
    private String customerpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerTel
     *
     * @mbg.generated
     */
    private String customertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerStar
     *
     * @mbg.generated
     */
    private Integer customerstar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.registerTime
     *
     * @mbg.generated
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerState
     *
     * @mbg.generated
     */
    private Integer customerstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerId
     *
     * @return the value of t_customer.customerId
     *
     * @mbg.generated
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerId
     *
     * @param customerid the value for t_customer.customerId
     *
     * @mbg.generated
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.paidId
     *
     * @return the value of t_customer.paidId
     *
     * @mbg.generated
     */
    public Integer getPaidid() {
        return paidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.paidId
     *
     * @param paidid the value for t_customer.paidId
     *
     * @mbg.generated
     */
    public void setPaidid(Integer paidid) {
        this.paidid = paidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerName
     *
     * @return the value of t_customer.customerName
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerName
     *
     * @param customername the value for t_customer.customerName
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerPassword
     *
     * @return the value of t_customer.customerPassword
     *
     * @mbg.generated
     */
    public String getCustomerpassword() {
        return customerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerPassword
     *
     * @param customerpassword the value for t_customer.customerPassword
     *
     * @mbg.generated
     */
    public void setCustomerpassword(String customerpassword) {
        this.customerpassword = customerpassword == null ? null : customerpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerTel
     *
     * @return the value of t_customer.customerTel
     *
     * @mbg.generated
     */
    public String getCustomertel() {
        return customertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerTel
     *
     * @param customertel the value for t_customer.customerTel
     *
     * @mbg.generated
     */
    public void setCustomertel(String customertel) {
        this.customertel = customertel == null ? null : customertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerStar
     *
     * @return the value of t_customer.customerStar
     *
     * @mbg.generated
     */
    public Integer getCustomerstar() {
        return customerstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerStar
     *
     * @param customerstar the value for t_customer.customerStar
     *
     * @mbg.generated
     */
    public void setCustomerstar(Integer customerstar) {
        this.customerstar = customerstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.registerTime
     *
     * @return the value of t_customer.registerTime
     *
     * @mbg.generated
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.registerTime
     *
     * @param registertime the value for t_customer.registerTime
     *
     * @mbg.generated
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerState
     *
     * @return the value of t_customer.customerState
     *
     * @mbg.generated
     */
    public Integer getCustomerstate() {
        return customerstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerState
     *
     * @param customerstate the value for t_customer.customerState
     *
     * @mbg.generated
     */
    public void setCustomerstate(Integer customerstate) {
        this.customerstate = customerstate;
    }
}