package com.chineseivy.bean;

import java.util.ArrayList;
import java.util.List;

public class GoodExample {
    protected String orderByClause;

    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_good
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public GoodExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_good
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodidIsNull() {
            addCriterion("goodId is null");
            return (Criteria) this;
        }

        public Criteria andGoodidIsNotNull() {
            addCriterion("goodId is not null");
            return (Criteria) this;
        }

        public Criteria andGoodidEqualTo(Integer value) {
            addCriterion("goodId =", value, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidNotEqualTo(Integer value) {
            addCriterion("goodId <>", value, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidGreaterThan(Integer value) {
            addCriterion("goodId >", value, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodId >=", value, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidLessThan(Integer value) {
            addCriterion("goodId <", value, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidLessThanOrEqualTo(Integer value) {
            addCriterion("goodId <=", value, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidIn(List<Integer> values) {
            addCriterion("goodId in", values, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidNotIn(List<Integer> values) {
            addCriterion("goodId not in", values, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidBetween(Integer value1, Integer value2) {
            addCriterion("goodId between", value1, value2, "goodid");
            return (Criteria) this;
        }

        public Criteria andGoodidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodId not between", value1, value2, "goodid");
            return (Criteria) this;
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopId is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopId is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Integer value) {
            addCriterion("shopId =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Integer value) {
            addCriterion("shopId <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Integer value) {
            addCriterion("shopId >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopId >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Integer value) {
            addCriterion("shopId <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Integer value) {
            addCriterion("shopId <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Integer> values) {
            addCriterion("shopId in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Integer> values) {
            addCriterion("shopId not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Integer value1, Integer value2) {
            addCriterion("shopId between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopId not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andRecommendidIsNull() {
            addCriterion("recommendId is null");
            return (Criteria) this;
        }

        public Criteria andRecommendidIsNotNull() {
            addCriterion("recommendId is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendidEqualTo(Integer value) {
            addCriterion("recommendId =", value, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidNotEqualTo(Integer value) {
            addCriterion("recommendId <>", value, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidGreaterThan(Integer value) {
            addCriterion("recommendId >", value, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidGreaterThanOrEqualTo(Integer value) {
            addCriterion("recommendId >=", value, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidLessThan(Integer value) {
            addCriterion("recommendId <", value, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidLessThanOrEqualTo(Integer value) {
            addCriterion("recommendId <=", value, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidIn(List<Integer> values) {
            addCriterion("recommendId in", values, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidNotIn(List<Integer> values) {
            addCriterion("recommendId not in", values, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidBetween(Integer value1, Integer value2) {
            addCriterion("recommendId between", value1, value2, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendidNotBetween(Integer value1, Integer value2) {
            addCriterion("recommendId not between", value1, value2, "recommendid");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceIsNull() {
            addCriterion("recommendPrice is null");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceIsNotNull() {
            addCriterion("recommendPrice is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceEqualTo(Double value) {
            addCriterion("recommendPrice =", value, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceNotEqualTo(Double value) {
            addCriterion("recommendPrice <>", value, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceGreaterThan(Double value) {
            addCriterion("recommendPrice >", value, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("recommendPrice >=", value, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceLessThan(Double value) {
            addCriterion("recommendPrice <", value, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceLessThanOrEqualTo(Double value) {
            addCriterion("recommendPrice <=", value, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceIn(List<Double> values) {
            addCriterion("recommendPrice in", values, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceNotIn(List<Double> values) {
            addCriterion("recommendPrice not in", values, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceBetween(Double value1, Double value2) {
            addCriterion("recommendPrice between", value1, value2, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andRecommendpriceNotBetween(Double value1, Double value2) {
            addCriterion("recommendPrice not between", value1, value2, "recommendprice");
            return (Criteria) this;
        }

        public Criteria andGoodnameIsNull() {
            addCriterion("goodName is null");
            return (Criteria) this;
        }

        public Criteria andGoodnameIsNotNull() {
            addCriterion("goodName is not null");
            return (Criteria) this;
        }

        public Criteria andGoodnameEqualTo(String value) {
            addCriterion("goodName =", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameNotEqualTo(String value) {
            addCriterion("goodName <>", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameGreaterThan(String value) {
            addCriterion("goodName >", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameGreaterThanOrEqualTo(String value) {
            addCriterion("goodName >=", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameLessThan(String value) {
            addCriterion("goodName <", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameLessThanOrEqualTo(String value) {
            addCriterion("goodName <=", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameLike(String value) {
            addCriterion("goodName like", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameNotLike(String value) {
            addCriterion("goodName not like", value, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameIn(List<String> values) {
            addCriterion("goodName in", values, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameNotIn(List<String> values) {
            addCriterion("goodName not in", values, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameBetween(String value1, String value2) {
            addCriterion("goodName between", value1, value2, "goodname");
            return (Criteria) this;
        }

        public Criteria andGoodnameNotBetween(String value1, String value2) {
            addCriterion("goodName not between", value1, value2, "goodname");
            return (Criteria) this;
        }

        public Criteria andOldpriceIsNull() {
            addCriterion("oldPrice is null");
            return (Criteria) this;
        }

        public Criteria andOldpriceIsNotNull() {
            addCriterion("oldPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOldpriceEqualTo(Double value) {
            addCriterion("oldPrice =", value, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceNotEqualTo(Double value) {
            addCriterion("oldPrice <>", value, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceGreaterThan(Double value) {
            addCriterion("oldPrice >", value, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("oldPrice >=", value, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceLessThan(Double value) {
            addCriterion("oldPrice <", value, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceLessThanOrEqualTo(Double value) {
            addCriterion("oldPrice <=", value, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceIn(List<Double> values) {
            addCriterion("oldPrice in", values, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceNotIn(List<Double> values) {
            addCriterion("oldPrice not in", values, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceBetween(Double value1, Double value2) {
            addCriterion("oldPrice between", value1, value2, "oldprice");
            return (Criteria) this;
        }

        public Criteria andOldpriceNotBetween(Double value1, Double value2) {
            addCriterion("oldPrice not between", value1, value2, "oldprice");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andActivityidIsNull() {
            addCriterion("activityId is null");
            return (Criteria) this;
        }

        public Criteria andActivityidIsNotNull() {
            addCriterion("activityId is not null");
            return (Criteria) this;
        }

        public Criteria andActivityidEqualTo(Integer value) {
            addCriterion("activityId =", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotEqualTo(Integer value) {
            addCriterion("activityId <>", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidGreaterThan(Integer value) {
            addCriterion("activityId >", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("activityId >=", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidLessThan(Integer value) {
            addCriterion("activityId <", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidLessThanOrEqualTo(Integer value) {
            addCriterion("activityId <=", value, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidIn(List<Integer> values) {
            addCriterion("activityId in", values, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotIn(List<Integer> values) {
            addCriterion("activityId not in", values, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidBetween(Integer value1, Integer value2) {
            addCriterion("activityId between", value1, value2, "activityid");
            return (Criteria) this;
        }

        public Criteria andActivityidNotBetween(Integer value1, Integer value2) {
            addCriterion("activityId not between", value1, value2, "activityid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidIsNull() {
            addCriterion("goodClassId is null");
            return (Criteria) this;
        }

        public Criteria andGoodclassidIsNotNull() {
            addCriterion("goodClassId is not null");
            return (Criteria) this;
        }

        public Criteria andGoodclassidEqualTo(Integer value) {
            addCriterion("goodClassId =", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidNotEqualTo(Integer value) {
            addCriterion("goodClassId <>", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidGreaterThan(Integer value) {
            addCriterion("goodClassId >", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodClassId >=", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidLessThan(Integer value) {
            addCriterion("goodClassId <", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidLessThanOrEqualTo(Integer value) {
            addCriterion("goodClassId <=", value, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidIn(List<Integer> values) {
            addCriterion("goodClassId in", values, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidNotIn(List<Integer> values) {
            addCriterion("goodClassId not in", values, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidBetween(Integer value1, Integer value2) {
            addCriterion("goodClassId between", value1, value2, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andGoodclassidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodClassId not between", value1, value2, "goodclassid");
            return (Criteria) this;
        }

        public Criteria andActivitypriceIsNull() {
            addCriterion("activityPrice is null");
            return (Criteria) this;
        }

        public Criteria andActivitypriceIsNotNull() {
            addCriterion("activityPrice is not null");
            return (Criteria) this;
        }

        public Criteria andActivitypriceEqualTo(Double value) {
            addCriterion("activityPrice =", value, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceNotEqualTo(Double value) {
            addCriterion("activityPrice <>", value, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceGreaterThan(Double value) {
            addCriterion("activityPrice >", value, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceGreaterThanOrEqualTo(Double value) {
            addCriterion("activityPrice >=", value, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceLessThan(Double value) {
            addCriterion("activityPrice <", value, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceLessThanOrEqualTo(Double value) {
            addCriterion("activityPrice <=", value, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceIn(List<Double> values) {
            addCriterion("activityPrice in", values, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceNotIn(List<Double> values) {
            addCriterion("activityPrice not in", values, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceBetween(Double value1, Double value2) {
            addCriterion("activityPrice between", value1, value2, "activityprice");
            return (Criteria) this;
        }

        public Criteria andActivitypriceNotBetween(Double value1, Double value2) {
            addCriterion("activityPrice not between", value1, value2, "activityprice");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andStandardIsNull() {
            addCriterion("standard is null");
            return (Criteria) this;
        }

        public Criteria andStandardIsNotNull() {
            addCriterion("standard is not null");
            return (Criteria) this;
        }

        public Criteria andStandardEqualTo(String value) {
            addCriterion("standard =", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotEqualTo(String value) {
            addCriterion("standard <>", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardGreaterThan(String value) {
            addCriterion("standard >", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardGreaterThanOrEqualTo(String value) {
            addCriterion("standard >=", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLessThan(String value) {
            addCriterion("standard <", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLessThanOrEqualTo(String value) {
            addCriterion("standard <=", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLike(String value) {
            addCriterion("standard like", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotLike(String value) {
            addCriterion("standard not like", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardIn(List<String> values) {
            addCriterion("standard in", values, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotIn(List<String> values) {
            addCriterion("standard not in", values, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardBetween(String value1, String value2) {
            addCriterion("standard between", value1, value2, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotBetween(String value1, String value2) {
            addCriterion("standard not between", value1, value2, "standard");
            return (Criteria) this;
        }

        public Criteria andGoodstateIsNull() {
            addCriterion("goodState is null");
            return (Criteria) this;
        }

        public Criteria andGoodstateIsNotNull() {
            addCriterion("goodState is not null");
            return (Criteria) this;
        }

        public Criteria andGoodstateEqualTo(Integer value) {
            addCriterion("goodState =", value, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateNotEqualTo(Integer value) {
            addCriterion("goodState <>", value, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateGreaterThan(Integer value) {
            addCriterion("goodState >", value, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodState >=", value, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateLessThan(Integer value) {
            addCriterion("goodState <", value, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateLessThanOrEqualTo(Integer value) {
            addCriterion("goodState <=", value, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateIn(List<Integer> values) {
            addCriterion("goodState in", values, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateNotIn(List<Integer> values) {
            addCriterion("goodState not in", values, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateBetween(Integer value1, Integer value2) {
            addCriterion("goodState between", value1, value2, "goodstate");
            return (Criteria) this;
        }

        public Criteria andGoodstateNotBetween(Integer value1, Integer value2) {
            addCriterion("goodState not between", value1, value2, "goodstate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateIsNull() {
            addCriterion("activtiyState is null");
            return (Criteria) this;
        }

        public Criteria andActivtiystateIsNotNull() {
            addCriterion("activtiyState is not null");
            return (Criteria) this;
        }

        public Criteria andActivtiystateEqualTo(Integer value) {
            addCriterion("activtiyState =", value, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateNotEqualTo(Integer value) {
            addCriterion("activtiyState <>", value, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateGreaterThan(Integer value) {
            addCriterion("activtiyState >", value, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateGreaterThanOrEqualTo(Integer value) {
            addCriterion("activtiyState >=", value, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateLessThan(Integer value) {
            addCriterion("activtiyState <", value, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateLessThanOrEqualTo(Integer value) {
            addCriterion("activtiyState <=", value, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateIn(List<Integer> values) {
            addCriterion("activtiyState in", values, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateNotIn(List<Integer> values) {
            addCriterion("activtiyState not in", values, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateBetween(Integer value1, Integer value2) {
            addCriterion("activtiyState between", value1, value2, "activtiystate");
            return (Criteria) this;
        }

        public Criteria andActivtiystateNotBetween(Integer value1, Integer value2) {
            addCriterion("activtiyState not between", value1, value2, "activtiystate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_good
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_good
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}