package com.chineseivy.bean;

public class LogisticsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logistics.shopId
     *
     * @mbg.generated
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logistics.orderId
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics.shopId
     *
     * @return the value of t_logistics.shopId
     *
     * @mbg.generated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics.shopId
     *
     * @param shopid the value for t_logistics.shopId
     *
     * @mbg.generated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics.orderId
     *
     * @return the value of t_logistics.orderId
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics.orderId
     *
     * @param orderid the value for t_logistics.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}