package com.chineseivy.bean;

import java.util.Date;

public class Logistics extends LogisticsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logistics.logisticsId
     *
     * @mbg.generated
     */
    private Integer logisticsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logistics.logisticsState
     *
     * @mbg.generated
     */
    private Integer logisticsstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logistics.logisticsLocation
     *
     * @mbg.generated
     */
    private String logisticslocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logistics.logisticsTime
     *
     * @mbg.generated
     */
    private Date logisticstime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics.logisticsId
     *
     * @return the value of t_logistics.logisticsId
     *
     * @mbg.generated
     */
    public Integer getLogisticsid() {
        return logisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics.logisticsId
     *
     * @param logisticsid the value for t_logistics.logisticsId
     *
     * @mbg.generated
     */
    public void setLogisticsid(Integer logisticsid) {
        this.logisticsid = logisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics.logisticsState
     *
     * @return the value of t_logistics.logisticsState
     *
     * @mbg.generated
     */
    public Integer getLogisticsstate() {
        return logisticsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics.logisticsState
     *
     * @param logisticsstate the value for t_logistics.logisticsState
     *
     * @mbg.generated
     */
    public void setLogisticsstate(Integer logisticsstate) {
        this.logisticsstate = logisticsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics.logisticsLocation
     *
     * @return the value of t_logistics.logisticsLocation
     *
     * @mbg.generated
     */
    public String getLogisticslocation() {
        return logisticslocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics.logisticsLocation
     *
     * @param logisticslocation the value for t_logistics.logisticsLocation
     *
     * @mbg.generated
     */
    public void setLogisticslocation(String logisticslocation) {
        this.logisticslocation = logisticslocation == null ? null : logisticslocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logistics.logisticsTime
     *
     * @return the value of t_logistics.logisticsTime
     *
     * @mbg.generated
     */
    public Date getLogisticstime() {
        return logisticstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logistics.logisticsTime
     *
     * @param logisticstime the value for t_logistics.logisticsTime
     *
     * @mbg.generated
     */
    public void setLogisticstime(Date logisticstime) {
        this.logisticstime = logisticstime;
    }
}