package com.chineseivy.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MarketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_market
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_market
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_market
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public MarketExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_market
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMarkidIsNull() {
            addCriterion("markId is null");
            return (Criteria) this;
        }

        public Criteria andMarkidIsNotNull() {
            addCriterion("markId is not null");
            return (Criteria) this;
        }

        public Criteria andMarkidEqualTo(Integer value) {
            addCriterion("markId =", value, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidNotEqualTo(Integer value) {
            addCriterion("markId <>", value, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidGreaterThan(Integer value) {
            addCriterion("markId >", value, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidGreaterThanOrEqualTo(Integer value) {
            addCriterion("markId >=", value, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidLessThan(Integer value) {
            addCriterion("markId <", value, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidLessThanOrEqualTo(Integer value) {
            addCriterion("markId <=", value, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidIn(List<Integer> values) {
            addCriterion("markId in", values, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidNotIn(List<Integer> values) {
            addCriterion("markId not in", values, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidBetween(Integer value1, Integer value2) {
            addCriterion("markId between", value1, value2, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkidNotBetween(Integer value1, Integer value2) {
            addCriterion("markId not between", value1, value2, "markid");
            return (Criteria) this;
        }

        public Criteria andMarkettimeIsNull() {
            addCriterion("marketTime is null");
            return (Criteria) this;
        }

        public Criteria andMarkettimeIsNotNull() {
            addCriterion("marketTime is not null");
            return (Criteria) this;
        }

        public Criteria andMarkettimeEqualTo(Date value) {
            addCriterion("marketTime =", value, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeNotEqualTo(Date value) {
            addCriterion("marketTime <>", value, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeGreaterThan(Date value) {
            addCriterion("marketTime >", value, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeGreaterThanOrEqualTo(Date value) {
            addCriterion("marketTime >=", value, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeLessThan(Date value) {
            addCriterion("marketTime <", value, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeLessThanOrEqualTo(Date value) {
            addCriterion("marketTime <=", value, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeIn(List<Date> values) {
            addCriterion("marketTime in", values, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeNotIn(List<Date> values) {
            addCriterion("marketTime not in", values, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeBetween(Date value1, Date value2) {
            addCriterion("marketTime between", value1, value2, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarkettimeNotBetween(Date value1, Date value2) {
            addCriterion("marketTime not between", value1, value2, "markettime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeIsNull() {
            addCriterion("marketStarTime is null");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeIsNotNull() {
            addCriterion("marketStarTime is not null");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeEqualTo(Date value) {
            addCriterion("marketStarTime =", value, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeNotEqualTo(Date value) {
            addCriterion("marketStarTime <>", value, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeGreaterThan(Date value) {
            addCriterion("marketStarTime >", value, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeGreaterThanOrEqualTo(Date value) {
            addCriterion("marketStarTime >=", value, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeLessThan(Date value) {
            addCriterion("marketStarTime <", value, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeLessThanOrEqualTo(Date value) {
            addCriterion("marketStarTime <=", value, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeIn(List<Date> values) {
            addCriterion("marketStarTime in", values, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeNotIn(List<Date> values) {
            addCriterion("marketStarTime not in", values, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeBetween(Date value1, Date value2) {
            addCriterion("marketStarTime between", value1, value2, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketstartimeNotBetween(Date value1, Date value2) {
            addCriterion("marketStarTime not between", value1, value2, "marketstartime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeIsNull() {
            addCriterion("marketEndTime is null");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeIsNotNull() {
            addCriterion("marketEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeEqualTo(Date value) {
            addCriterion("marketEndTime =", value, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeNotEqualTo(Date value) {
            addCriterion("marketEndTime <>", value, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeGreaterThan(Date value) {
            addCriterion("marketEndTime >", value, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("marketEndTime >=", value, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeLessThan(Date value) {
            addCriterion("marketEndTime <", value, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeLessThanOrEqualTo(Date value) {
            addCriterion("marketEndTime <=", value, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeIn(List<Date> values) {
            addCriterion("marketEndTime in", values, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeNotIn(List<Date> values) {
            addCriterion("marketEndTime not in", values, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeBetween(Date value1, Date value2) {
            addCriterion("marketEndTime between", value1, value2, "marketendtime");
            return (Criteria) this;
        }

        public Criteria andMarketendtimeNotBetween(Date value1, Date value2) {
            addCriterion("marketEndTime not between", value1, value2, "marketendtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_market
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_market
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}