package com.chineseivy.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.orderId
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customerId
     *
     * @mbg.generated
     */
    private Integer customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.orderNum
     *
     * @mbg.generated
     */
    private Integer ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.boughtNumber
     *
     * @mbg.generated
     */
    private Integer boughtnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.boughtStandard
     *
     * @mbg.generated
     */
    private String boughtstandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.boughtPrice
     *
     * @mbg.generated
     */
    private BigDecimal boughtprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.paidState
     *
     * @mbg.generated
     */
    private Integer paidstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.confirmedTime
     *
     * @mbg.generated
     */
    private Date confirmedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.loseState
     *
     * @mbg.generated
     */
    private Integer losestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receivedTime
     *
     * @mbg.generated
     */
    private Date receivedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.cancelState
     *
     * @mbg.generated
     */
    private Integer cancelstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.deleteState
     *
     * @mbg.generated
     */
    private Integer deletestate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.orderId
     *
     * @return the value of t_order.orderId
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.orderId
     *
     * @param orderid the value for t_order.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customerId
     *
     * @return the value of t_order.customerId
     *
     * @mbg.generated
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customerId
     *
     * @param customerid the value for t_order.customerId
     *
     * @mbg.generated
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.orderNum
     *
     * @return the value of t_order.orderNum
     *
     * @mbg.generated
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.orderNum
     *
     * @param ordernum the value for t_order.orderNum
     *
     * @mbg.generated
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.createTime
     *
     * @return the value of t_order.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.createTime
     *
     * @param createtime the value for t_order.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.boughtNumber
     *
     * @return the value of t_order.boughtNumber
     *
     * @mbg.generated
     */
    public Integer getBoughtnumber() {
        return boughtnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.boughtNumber
     *
     * @param boughtnumber the value for t_order.boughtNumber
     *
     * @mbg.generated
     */
    public void setBoughtnumber(Integer boughtnumber) {
        this.boughtnumber = boughtnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.boughtStandard
     *
     * @return the value of t_order.boughtStandard
     *
     * @mbg.generated
     */
    public String getBoughtstandard() {
        return boughtstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.boughtStandard
     *
     * @param boughtstandard the value for t_order.boughtStandard
     *
     * @mbg.generated
     */
    public void setBoughtstandard(String boughtstandard) {
        this.boughtstandard = boughtstandard == null ? null : boughtstandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.boughtPrice
     *
     * @return the value of t_order.boughtPrice
     *
     * @mbg.generated
     */
    public BigDecimal getBoughtprice() {
        return boughtprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.boughtPrice
     *
     * @param boughtprice the value for t_order.boughtPrice
     *
     * @mbg.generated
     */
    public void setBoughtprice(BigDecimal boughtprice) {
        this.boughtprice = boughtprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.paidState
     *
     * @return the value of t_order.paidState
     *
     * @mbg.generated
     */
    public Integer getPaidstate() {
        return paidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.paidState
     *
     * @param paidstate the value for t_order.paidState
     *
     * @mbg.generated
     */
    public void setPaidstate(Integer paidstate) {
        this.paidstate = paidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.confirmedTime
     *
     * @return the value of t_order.confirmedTime
     *
     * @mbg.generated
     */
    public Date getConfirmedtime() {
        return confirmedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.confirmedTime
     *
     * @param confirmedtime the value for t_order.confirmedTime
     *
     * @mbg.generated
     */
    public void setConfirmedtime(Date confirmedtime) {
        this.confirmedtime = confirmedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.loseState
     *
     * @return the value of t_order.loseState
     *
     * @mbg.generated
     */
    public Integer getLosestate() {
        return losestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.loseState
     *
     * @param losestate the value for t_order.loseState
     *
     * @mbg.generated
     */
    public void setLosestate(Integer losestate) {
        this.losestate = losestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receivedTime
     *
     * @return the value of t_order.receivedTime
     *
     * @mbg.generated
     */
    public Date getReceivedtime() {
        return receivedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receivedTime
     *
     * @param receivedtime the value for t_order.receivedTime
     *
     * @mbg.generated
     */
    public void setReceivedtime(Date receivedtime) {
        this.receivedtime = receivedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.cancelState
     *
     * @return the value of t_order.cancelState
     *
     * @mbg.generated
     */
    public Integer getCancelstate() {
        return cancelstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.cancelState
     *
     * @param cancelstate the value for t_order.cancelState
     *
     * @mbg.generated
     */
    public void setCancelstate(Integer cancelstate) {
        this.cancelstate = cancelstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.deleteState
     *
     * @return the value of t_order.deleteState
     *
     * @mbg.generated
     */
    public Integer getDeletestate() {
        return deletestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.deleteState
     *
     * @param deletestate the value for t_order.deleteState
     *
     * @mbg.generated
     */
    public void setDeletestate(Integer deletestate) {
        this.deletestate = deletestate;
    }
}