package com.chineseivy.bean;

public class WarehouseKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warehouse.goodId
     *
     * @mbg.generated
     */
    private Integer goodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warehouse.shopId
     *
     * @mbg.generated
     */
    private Integer shopid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warehouse.goodId
     *
     * @return the value of t_warehouse.goodId
     *
     * @mbg.generated
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warehouse.goodId
     *
     * @param goodid the value for t_warehouse.goodId
     *
     * @mbg.generated
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warehouse.shopId
     *
     * @return the value of t_warehouse.shopId
     *
     * @mbg.generated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warehouse.shopId
     *
     * @param shopid the value for t_warehouse.shopId
     *
     * @mbg.generated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }
}